### ISSUE TITLE
Message: Process unexpectedly closed with status 0

### ISSUE THREAD

**Issue by SoloKun** [imcyx/UESTC_Report#1]
这几天发现不能打卡，一直报错
`Message: Process unexpectedly closed with status 0`
发现是selenium太新，而shell的库太旧，就把两个脚本改成最新就解决了。
可能其它同学也会出这个问题，就发这儿了。

**Comment by imcyx** [comment]
收到，问题已定位，是由于Firefox在执行时检测到版本过低，提示自动更新，阻止了Geckodriver的自动化控制。
目前已经通过下载更新的Firefox和对应的Geckodriver解决。
考虑后续会增加前置脚本，在安装二者之前进行版本判断。

感谢反馈！
